### PR TITLE
Introduce Fake API Layer

### PR DESCRIPTION
**Pull request by jalcine**
## Feature idea (if an idea)

This aims to provide frontend developers with mock models that they can work with for the sake of testing. It'd make use of the Mirage and Pretender tools to allow for our models to be pushed in a mock fashion.

## Things to Fake

- [ ] ~~Signing in~~
- Fetching list of
  - [ ] companies
  - [ ] perks
  - [ ] locations

This is a small list and will be expanded over time.

### CODE REVIEW

**Comment by jalcine** [comment]
Leveraging notes from [here][1] about faking GraphQL.

[1]: https://emberway.io/faking-graphql-with-ember-cli-mirage-811e83937a5b

**Comment by cattsmall** [comment]
This sounds correct to me! Assuming companies includes some ratings, I can't think of anything else we need to get started.

**Comment by jalcine** [comment]
Word. That'll be in here then.

**Comment by chadtomkiss** [comment]
@jalcine I'm wondering whether this would be a good time to introduce front-end tests as well? So that when we switch the implementation we can be confident we didn't miss something?

**Comment by chadtomkiss** [comment]
Not sure how far along you are with this, but https://github.com/marmelab/json-graphql-server looks v handy.

Will turn a JSON object with defined data / relationships into GraphQL queries 🔥

**Comment by jalcine** [comment]
@chadtomkiss Oh, that looks _good_! The only thing I can see with this is having to spin up another dependency while working on the client side. I'd want to reduce the number of painpoints/servers as possible.

That said, I'm interested to see what can be done with that - feel free to tinker away!

**Comment by chadtomkiss** [comment]
We could maybe deploy it so that they have an actual URL to hit?

**Comment by chadtomkiss** [comment]
Happy to test it out and see how it looks tomorrow.

**Comment by jalcine** [comment]
That works! I'm still working on the kinks on the automatic deployment aspect of things.

**Comment by jalcine** [comment]
Dropping 'sign in' for now.

**Comment by jalcine** [comment]
All of this isn't needed anymore. Nuking.

**Pull request closed without merging**
