### PR TITLE
[Improvement] Make Ember Ready to Go

### PR DESCRIPTION
**Pull request by jalcine**
This dumps some stuff for Ruby and focuses this repository on Node/Ember.

This references and/or relates to issues #14.

--------

- [x] Import old styles.
- [x] Make minimal CSS framework.
- [x] Remove Sinatra and Ruby stuff.
- [x] Correct Metadata.
- [x] Ensure we can ping to the API in development.

### CODE REVIEW

**Comment by jalcine** [comment]
So @cattsmall: I'm going to import the old styles of the site prior just so we can get to a point where we're using the familar styles but under Ember. I know you plan to port the styling to be friendlier so just looking for your thoughts here.

**Comment by jalcine** [comment]
I'm going to chip away at the imported styles to make some sane defaults (type, button styles, colors) to help with making the new CSS framework.

**Comment by cattsmall** [comment]
SOON

**Comment by chadtomkiss** [comment]
With regards to the minimal CSS framework.. have you seen http://tachyons.io?

It's a bit jarring at first, but it makes building components hella fast. You can get a lot done without even having to touch CSS.

**Comment by jalcine** [comment]
@chadtomkiss: I have! I personally enjoy using it  (it's on my personal site). @cattsmall's point on design and mentioned in Gitter that we're be taking a different approach however.

**Comment by jalcine** [comment]
Going to drop the pinging of the API for now.

**Pull request merged**
