### PR TITLE
Removing package ember-cli-sentry because causes error with initial i…

### PR DESCRIPTION
**Pull request by TrashyTown**
Removing package ember-cli-sentry because causes error when running with initial install

### CODE REVIEW

**Comment by jalcine** [comment]
Sentry is the tool that'd be used for sending errors. Instead of completely removing it, can you open an issue about this failure and see if there's something that can be done to fix your problem?

Thanks for opening this nonetheless!

**Comment by jalcine** [comment]
Just tried this in a clean env with no isues. Did you run `bower install` after running `npm install`? The documentation doesn't tell you to run that (yet) but it's a required test.

**Comment by jalcine** [comment]
*required step, apologies.

**Comment by jalcine** [comment]
@TrashyTown Can you copy + paste the error you see here?

**Comment by jalcine** [comment]
Ah, okay. Just ran into this myself. WIll work ona fix.

**Comment by jalcine** [comment]
Sentry was missing some configuration option. Please try pulling `develop` and testing that @TrashyTown.

**Comment by cattsmall** [comment]
@jalcine @TrashyTown sounds like this PR is no longer needed. Is that correct?

**Comment by jalcine** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

That’s correct!
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZ9ofAAAoJEDbNdyi9/Wb/fcsP/iiahe/aO3xiBBQOEnQPtAdd
L/dWlZP6A9pZNhvPB5y3cNus26560ZPbegchYTtVlJsA1pR0qnOov3L7oYUjDNOr
l3K/WH62otUSQ87LW0/p2dsSZtLf+oVh/91/vaeaiyqoah6NvVd8AhI95pOkS2/C
78E4z8c1bVwhIyp+f2J6ko2E3y0gRgC+qdKd22TNr04al127980Y57N5xCTzC+JJ
AZOgJs4rvUWp6/Ts7RQumeJYs+Ga3ipdT06eQ28WWXL3ybgSJvO+UsiIeC4RGSZn
TH1TkclgALOMRRcg7AvDjc3qR1/TSlpF0SPzzrvqR1Mkfn5Xfq/tQmzXWR6nzu4e
hEZz2otWaVBpwLKDDBrvYQBz8dy+p9/IxO9pufGSXSAGc5ABOa/2VM58J9lNu4tB
LlOlv15Qq+XhSh4+49pvoWsk7lel7ToO4dIBudcr+r5YquXCSetppUNt2oQUBkAP
vG0i+H040485LUUxrABjjtqdb6zBnW0CNT2kSX1XJwD3m7MzlhdpRJ1XuMA4qhu+
PUqahD/K/nSdU0uCHC8sihIXPjFCbalHabfIcjqjV5BZk7iGBmUnKOPrYpEZXrPI
ui0ks6dWHcr/MCKjR864iX+31WcpTIL09pNMS+rjZmiAMLh0ysWwUFN8upBSmpBt
mlVrEtHo+jsOzEzZUD+u
=kifl
-----END PGP SIGNATURE-----

**Comment by jalcine** [comment]
Er, there was no need for that commit. I'll just close this.

Thanks for your submission @TrashyTown!

**Pull request closed without merging**
