### PR TITLE
Creation of Animation Guidelines

### PR DESCRIPTION
**Pull request by adekunleoduye**
## Description
Created a basic css animation file with a couple of vars and keyframes rules. This will need to be adjusted once the design systems is up and running.

## Context

Related to roadmap item(s):

- https://github.com/GoodForPoC/GoodForPoC/issues/45

## Reviewers

@GoodForPoC/owners @GoodForPoC/moderators

### CODE REVIEW

**Comment by jalcine** [comment]
The build failed unexpectedly. I'm going to run it locally and see what's up. I'll approve this accordingly.

**Comment by jalcine** [comment]
This is all good - I can merge if you're comfortable with this @cattsmall

**Comment by cattsmall** [comment]
Thumbs up from me!​

**Comment by jalcine** [comment]
Merging in 5.

**Comment by jalcine** [comment]
🎊

**Pull request merged**
